{%set name = "snakefood" %}
{%set version = "1.4" %}
{%set hash_type = "sha256" %}
{%set hash_val = "295784668032254e7391ca99ba7060edd3ae4eca1a330ac11627b18ab5923b77" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - snakefood
    - snakefood.fallback
  requires:
    - nose
  commands:
    - sfood -h
    - sfood-graph -h
    - sfood-cluster -h
    - sfood-checker -h
    - sfood-imports -h
    - nosetests

about:
  home: http://furius.ca/snakefood
  license: GPL 2.0
  summary: 'Dependency Graphing for Python'

extra:
  recipe-maintainers:
    - pmlandwehr
