{% set name = "snakefood" %}
{% set version = "1.4" %}
{% set hash_val = "295784668032254e7391ca99ba7060edd3ae4eca1a330ac11627b18ab5923b77" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  skip: True  # [py3k]
  number: 1002
  script: python setup.py install --record=record.txt

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - snakefood
    - snakefood.fallback

about:
  home: http://furius.ca/snakefood
  license: GPL-2.0
  license_file: COPYING
  summary: 'Dependency Graphing for Python'

extra:
  recipe-maintainers:
    - pmlandwehr
