travis:
  secure:
    BINSTAR_TOKEN: jRFDMHX3OrW4K7QqA/9jk8i+NofpGcnVIn6iIbtwePxWLbfyVKCSU8qQzw9vzf6mRMZZ3SwLWgcu7CBCqePTC5HpCfnYYLkXuUw46EkH3uArIhL1U9Qv6KSJl8Urn1HFoxZpN12A69oWS85ek5Zgm2QMIi7dcgGf9jpMmE4fybQi6Z2N42w5VMiXctv7M+ZDJaK4/ZqP5lR03xGnJGC8PIu1A48yMH34CS+lBnwU33g1SvJrO8j4yTXUusaRjaEkBjiStgbP2Mp4P6DYmxjo8Ql6i3gTMXdsYAngwx/GgciMeOLzKDx5qHsL/xQxwKLUZY3mPXqDl4eb9C451BbYa6HxLbbjSeos0rdShaoy9AVj3HU4BTotfJakLp2nEKezQljIIRI28vjjxphin73xmVu876qBcUvOXOuFu/FV5cwrdSChI7HusTXX1+zlgfHGhQ9MLfd1Z2STUNT6i1hYIHwhAvc1AMK35ge/5w7VexbZr57O5afHuQOCayCtN62FUvNTloKr38ZlC39N32JuZWLti/Ce09/oST7IYVg2YiQdY7ZJe4F2IBlxg9CrSGvS+a9BtbpUrI+OJIPSvvaKCcsXKPVOHcLQfoIQrgJhfBhn8yaUQQ34nVCkK/huFd00usb34sOPkir4bZsJtctd4Men83nwuCpQ8cmypM7vQL0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
