travis:
  secure:
    BINSTAR_TOKEN: hstXYf4U+zYYwYonq+mYsG9J+XQXHKTVutYFHhb3K4FidRR/08ptH0LekVHYLBQKCMg/s9Bq40bolR8FfmO+s4NFopky6JcCn128mZ+p/2LsFIQK3fgNlBLQTDJFmYX1PaxfIN3EGW1fOqtJrBuTregOXV4pTJamxpKpriWtELiQ7KegrSXNnu8EsBpOxFV+0J9EeMx4w95obSAcuB+Z/4nCRryX7TlLLcsyET6DKxvDvvd70EMVHxSTFj7afnOk7xFiBp6r9K1CziZm8lnWABQy7guaP1NsYmRb4pNX/iOj8VxINyw0A09IKYMqszTaSPW7iBPKlxTHsAiWa8V5X3LB6wuQvQl9pCeEyrAaA51IzyAJeR1Lpey49pTlGbqm14rBXUW1ZA/IyIxcv9OlGE59OZ2h8Km/oFyWZcKDMnp6Ry7ZAaukmc+ZWZ9TJJsabc7rJgZPU54woE0FtaTmQJY5lJuxUJIy7VFbGb1j0V4yLigxzQ7/CabuqptizMHFJ8mg3gYQp+oiSKdmgxFfxe+UtHpAx7v6uGl54xBZBtv/WnWq0xCozBLbb78s/zDKQO44vbamuHYasFZL40T0ygBCu9tcZBYsRd4W3rz/r1YY16u4xPP3CqLNJQBW1ckYwRugQiIpWTSRA8ZonZktyjDDgDuGDSuOLtmSVqwJ0P4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
